services:

  mysqldb:
    container_name: mysqlcontainer
    image: mysql
    restart: unless-stopped
    volumes: 
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - db_data_O:/var/lib/mysql #If you don't define this, logging into a workbench will prompt errors
    ports: 
       - 3307:3306 # mapping from local port to container port
    expose:
      - 3307
    env_file:
       - mysqlenvvariable.env
    networks:
      - internalnet

  phpmyadmin:
    container_name: phpmyadmincontainer
    image: phpmyadmin
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 8081:80
    environment:
       PMA_HOST: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    restart: always
    ports: 
      - 3000:3000 # mapping from local port to container port
    expose:
      - 3000
    depends_on:
      - mysqldb
    env_file:
      - nodeapp.env     
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
       
volumes:
  db_data_O: