services:

  mysqldb:
    container_name: mysqlcontainer
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes: 
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - db_data:/var/lib/mysql #If you don't define this, logging into a workbench will prompt errors
    ports: 
       - 3308:3306 # mapping from local port to container port
    expose:
      - 3308
    environment:      
      MYSQL_DATABASE: portfoliodb
      MYSQL_USER: Godwin
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldbservice
    networks:
      - internalnet

  phpmyadmin:
    container_name: phpmyadmincontainer
    image: phpmyadmin
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 8081:80
    environment:
       PMA_HOST: mysqldb
    networks:
      - internalnet

  # postgredb:
  #  container_name: postgresqlcontainer
  #  image: postgres
  #  environment:
  #      POSTGRES_USER: Godwin
  #      POSTGRES_PASSWORD: secret
  #  ports:
  #    - 5432:5432      
  #  volumes:
  #     - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
  #  networks:
  #     - internalnet


  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    ports: 
      - 3000:3000 # mapping from local port to container port
    expose:
      - 3000
    depends_on:
      - mysqldb
    environment:
      DB_NAME: portfoliodb
      DB_USER: admin
      DB_HOST: mysqldb
      DB_PASSWORD: root
      DB_PORT: 3307
      SERVER_PORT: 3000 # container port
      DB_CONNECTION_LIMIT: 10
      SERVICE_TAGS: prod
      SERVICE_NAME: Nodeappservice      
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
       
volumes:
  db_data: