apiVersion: v1
kind: Pod
metadata:
  name: portfolio-mysql-pod
  labels:
    environment: production
    app: portfolio-mysql-pod-aws
spec:
  containers:
  - name: portfolio-mysql-container
    image: daddykiki/potfoliodatabase
    ports:
    - containerPort: 80